Bump wait for read only endpoints timeout 5 sec -> 5 min (#156)
We should wait until read-only endpoints appears
and NOT aborting on timeout 5 seconds on slow GH runners.

> Traceback (most recent call last):
>   File "/home/runner/work/mysql-operator/mysql-operator/tests/integration/relations/test_database.py", line 278, in test_read_only_endpoints
>     for attempt in AsyncRetrying(stop=stop_after_delay(5), wait=wait_fixed(20)):
>   File "/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/_asyncio.py", line 62, in __iter__
>     raise TypeError("AsyncRetrying object is not iterable")
> TypeError: AsyncRetrying object is not iterable

Waiting for 5 minutes instead of 5 seconds.

Co-authored-by: Paulo Machado <paulo.machado@canonical.com>